version: '3.3'
services:
    prometheus-vmware-exporter:
        restart: always
        container_name: prometheus-vmware-exporter
        ports:
          - 9512:9512
        environment:
            - ESX_HOST=<ip_address_or_host>
            - ESX_USERNAME=<username>
            - ESX_PASSWORD=<password>
            - ESX_LOG=debug
        image: jnewc/prometheus-vmware-exporter:latest
